### ISSUE TITLE
429 Too Many Requests

### ISSUE THREAD

**Issue by khromov** [mpolden/ipd#26]
Ran maybe 2-3 requests on https://ifconfig.co/ and now get `429 Too Many Requests`. Even from curl:

```
chip@chip:~$ curl ifconfig.co
429 Too Many Requests
```

**Comment by wujunchuan** [comment]
It is a protection mechanism to prevent waste resources

**Comment by khromov** [comment]
Sure, but it needs to have sane defaults. 2-3 requests/ip are not sane defaults, it needs to be in the hundreds or thousands per hour.

Also, this project can be made with a one-liner in most programming languages, so I doubt there is a big difference performance-wise between showing the actual IP and the `429` error. 😉

**Comment by mpolden** [comment]
The current limit is in place to prevent abuse and conserve resources. If you want an unlimited service you are free to host one yourself.

**Comment by khromov** [comment]
Wow, I'm stunned that rather than investigate whether the resource limits are correctly configured on your site, you ignore what I said (i made 5 requests tops, far from "unlimited") and ask me to use another service. I will, thank you very much.

**Comment by mpolden** [comment]
I know what the limit is and I carefully chose it based on the traffic patterns of ifconfig.co. The limit is not up for debate, so I'm locking this conversation.

Furthermore, this as a free service (including the code), so you are not entitled to *anything*.
