### ISSUE TITLE
Adjust max requests from IP.

### ISSUE THREAD

**Issue by blade2005** [mpolden/ipd#27]
I'm not doing this to incite anything however I looked through the code(Go is not a language I'm familiar with overly much) but I did not see where the 429 was coming from. Is this being handled in a forward facing proxy?

**Comment by mpolden** [comment]
That is correct. The rate limiting is handled by Nginx. The rate limit is in place to:

a) ensure a reliable service for everyone, and
b) conserve resources (e.g. bandwidth)

To accomplish this, automated clients should not request updates more than once per minute. I will add some documentation that clarifies this expectation.
