### ISSUE TITLE
IPv6 records are gone

### ISSUE THREAD

**Issue by FernandoMiguel** [mpolden/ipd#28]
accessing ifconfig.co via IPv6 , seems to show no DNS records.
https://dns.google.com/query?name=ifconfig.co&type=AAAA&dnssec=true

**Comment by mpolden** [comment]
IPv6 support has been removed for the time being as SixXS is shutting down: https://www.sixxs.net/sunset/

**Comment by FernandoMiguel** [comment]
I was aware SixXS was closing but how is that of impact for ifconfig.co service and all of us that have native IPv6?

**Comment by mpolden** [comment]
IPv6 connectivity for ifconfig.co was provided by SixXS.

**Comment by FernandoMiguel** [comment]
what are the options of deploying this on another provider with native IPv6?
aws, ovh, etc ?

**Comment by mpolden** [comment]
IPv6 support may return at some point, but I have no immediate plans to fix it. You are free to host your own version on whatever provider you want.

**Comment by HLFH** [comment]
@mpolden https://en.wikipedia.org/wiki/List_of_IPv6_tunnel_brokers

I would suggest to migrate to [Hurricane](https://tunnelbroker.net/).

> You are free to host your own version on whatever provider you want.

I will do that.
You should update the README.md to say that your own instance does not offer IPv6 but that your users could set up their own instance with IPv6 support if they need to. Or I can make a small PR about that. What do you think?
