### ISSUE TITLE
wget usage

### ISSUE THREAD

**Issue by mnp** [mpolden/ipd#30]
I think wget examples should be shown as:

```
$ wget -qO- ifconfig.co/ip
11.22.33.44
```

There are some flavors of wget, such as the builtin one in busybox, which will display the whole HTML page when the short form `ifconfig.co` is given.  Using the `/ip` form appears to work fine for both GNU and busybox wget flavors.

**Comment by mpolden** [comment]
Yes, `/ip` always work as it doesn't try to sniff the user-agent, this behaviour is documented on https://ifconfig.co/.

Do you know which user-agent busybox wget uses? Maybe we can add that one.

**Comment by mnp** [comment]
The server will see something like this:
```console
GET /foo HTTP/1.1
Host: localhost
User-Agent: Wget
Connection: close
```

Here's the agent itself.
```console
$ docker run -it busybox wget --help
BusyBox v1.26.2 (2017-03-09 00:04:38 UTC) multi-call binary.

Usage: wget [-c|--continue] [--spider] [-q|--quiet] [-O|--output-document FILE]
       	[--header 'header: value'] [-Y|--proxy on/off] [-P DIR]
       	[-U|--user-agent AGENT] [-T SEC] URL...

Retrieve files via HTTP or FTP

       	--spider       	Spider mode - only check file existence
       	-c     		Continue retrieval of aborted transfer
       	-q     		Quiet
       	-P DIR 		Save to DIR (default .)
       	-T SEC 		Network read timeout is SEC seconds
       	-O FILE		Save to FILE ('-' for stdout)
       	-U STR 		Use STR for User-Agent header
       	-Y on/off      	Use proxy
```
