### ISSUE TITLE
Include country ISO code in response, not just english name

### ISSUE THREAD

**Issue by TheRealMarnes** [mpolden/ipd#43]
I'd like to request the country ISO code to be included in the json response, not only the english name of the country, if possible. I assume you actually get the ISO code from your database but then translate it to the english name with a lookup... If not, I guess this request isn't valid.

The reason for this is that a country is uniquely identified with an ISO code, and that's the system that's used in lookups like country-to-flag services. An ISO code is much easier and safer for an API consumer to work with than a localized name.

```json
{
	"ip": "foo",
	"ip_decimal": 0,
	"country": "Belgium",
	"isoCountry": "BE",
	"city": "Unknown",
	"hostname": "isp.internet"
}
```

**Comment by mpolden** [comment]
Fixed by #45.

**Comment by TheRealMarnes** [comment]
Whenabouts will this change be deployed on ifconfig.co?

**Comment by mpolden** [comment]
Now.

**Comment by TheRealMarnes** [comment]
Working beautifully, thanks 👍
