### ISSUE TITLE
Add Access-Control-Allow-* headers

### ISSUE THREAD

**Issue by mkurz** [mpolden/ipd#49]
Hi, 

Looking at https://github.com/mpolden/ipd/issues/21#issuecomment-232778417 it looks like these headers were present already:
```
Access-Control-Allow-Methods: GET
Access-Control-Allow-Origin: *
```

**Comment by mpolden** [comment]
The only reason I see for having CORS is that you want to show responses from this service on a different domain, using XHR. In that case it makes more sense to host `ipd` yourself so that's why I removed them.

**Comment by stvhanna** [comment]
@mpolden How to add custom headers to the Docker deployment to allow for using the service through XHR?
I tried `-H Access-Control-Allow-Origin: *` but it didn't work.
