### ISSUE TITLE
curl getting 522 from CloudFlare

### ISSUE THREAD

**Issue by faultylee** [mpolden/ipd#50]
Hi, thanks for this great service. I only get to know about this service from another [blog](https://medium.com/@dbclin/a-bash-script-to-update-an-existing-aws-security-group-with-my-new-public-ip-address-d0c965d67f28).

Btw, as I'm trying it out, I'm setting 522 from CloudFlare, and all command takes about 30 seconds to respond. Below is what I've tried.
``` bash
curl ipconfig.co
curl https://ipconfig.co
curl ipconfig.co/json
curl -H 'Accept: text/plain' ipconfig.co
curl -H 'Accept: text/plain' -A 'curl/7.26.0' ipconfig.co #took the user-agent from one of the test file here
```

All getting the same output (snipped)
```
<title>ipconfig.co | 522: Connection timed out</title>
...
    <h2>What happened?</h2>
    <p>The initial connection between Cloudflare's network and the origin web server timed out. As a result, the web page can not be displayed.</p>
...
```
`wget -qO- ipconfig.co` results in timeout

No issue when visiting the page using a browser.

I proceed to test using the browsers request header and it works, then trim down to the minimum that works, and found that it somehow having `-H 'pragma: no-cache'` helps, then it will continue to work without it. But I can't replicate this 100%.

Is this related to issues caused by Cloudflare on other services lately? Or I'm doing something wrong here?

**Comment by mpolden** [comment]
The address for this service is i**f**config.co, it's unrelated to i**p**config.co in your examples.
